---@class poetry.PluginOpt
---@field enabled boolean: whether to enable the plugin
---@field opts? table: plugin-specific options

---@class poetry.Options
---@field plugins table<string, poetry.PluginOpt>: poetry plugins configuration (keyed by plugin name)
---@field lsp? string: the name of the LSP client to use (default: "pyright")
---@field fallback_envs? string[]: Python virtual environment directory names to search if Poetry env is not found
---@field keymaps? table: additional keymaps to add via which-key

local M = {}
local state = {
	wk_gp = "Poetry",
	default_lsp = "pyright",
	fallback_envs = { -- generated by AI
		".venv",
		"venv",
		".env",
		"env",

		".poetry_venv",
		".virtualenv",
		"virtualenv",
		".pipenv",
		"pipenv",
		".direnv",
		"direnv",

		"venv3",
		"venv2",
		"pyenv",
		".pyenv",
		"py-venv",
		"python-env",
		"python_env",
		"py_env",
		"pyenv-virtualenv",

		".venv-dev",
		".venv-prod",
		".venv-test",
		".venv-local",
		".venv-build",
		".venv-ci",
		".venv-env",
		".env-dev",
		".env-prod",
		".env-test",
		".env-local",

		".venv-api",
		".venv-worker",
		".venv-auth",
		".venv-backend",
		".venv-frontend",
		".venv-server",
		".venv-client",
		".venv-app",

		".snake",
		"snake",
		".cobra",
		"cobra",
		".kobra",
		"kobra",
		".sandbox",
		"sandbox",
		".lab",
		"lab",
		".envs",
		"envs",

		"venv_env",
		"virtual_env",
		"virtual-env",
		"python-venv",
		"pythonvenv",

		"venv_env",
		"venv_local",
		"env_local",
		".venv_local",
		".env_local",

		"ENV",
		"VENV",
		".VENV",
		".ENV",
	},
	keymaps = {},
}

--- Registers keymaps for the Poetry plugin using which-key.nvim.
--- Creates a "<leader>p" prefix group and adds the default "<leader>pd" keymap
--- to reset the LSP environment. Additional keymaps can be merged in.
---
--- @param lsp poetry.LSP: The LSP module with methods like `lsp.reset`
--- @param keymaps table: Additional which-key keymap definitions to merge
local function overall_keymaps(lsp, keymaps)
	local wk = require("which-key")

	wk.add({
		{ "<leader>p", group = state.wk_gp },
		vim.list_extend({
			{
				mode = "n",
				"<leader>pd",
				lsp.reset,
				desc = "Disable Poetry LSP Environment setup",
			},
		}, keymaps),
	})
end

--- Initializes the poetry.nvim plugin with the given configuration. Loads the specified LSP client, sets up enabled plugins, registers keymaps,
--- and configures the LSP with fallback environment paths.
---
--- @param opts poetry.Options: Configuration options for the plugin
M.setup = function(opts)
	local o = opts or {}
	o.plugins = o.plugins or {}
	o.lsp = o.lsp or state.default_lsp
	-- Extend fallback environments, prepending user-defined ones to global fallbacks.
	o.fallback_envs = vim.list_extend(o.fallback_envs or {}, state.fallback_envs)

	---@type poetry.LSP
	local lsp = require(string.format("lsps.%s", o.lsp))
	-- If 'require' returns 'true', it indicates the module was not found or failed to load correctly.
	if lsp == true then
		vim.notify("LSP not found or not supported", vim.log.levels.ERROR, {})
		return
	end

	for plugin_name, plugin_opts in pairs(o.plugins) do
		if not plugin_opts.enabled then
			goto continue
		end

		-- TODO: add a way to user define custom plugin setup from his own config

		---@type poetry.Plugin
		local plugin = require(string.format("poetry_plugins.%s", plugin_name))
		if plugin == true then
			vim.notify(string.format("Plugin %s not found", plugin_name), vim.log.levels.ERROR, {})
			return
		end

		plugin.setup(plugin_opts.opts or {})

		::continue::
	end

	overall_keymaps(lsp, opts.keymaps or {})
	lsp.configure({ fallback_envs = o.fallback_envs })
end

return M
